# Eager Execution


TensorFlow 引入了「Eager Execution」動態圖模式，這個模式在TensorFlow2.0為預設模式，不同與以往的靜態圖模式需要建立計算圖才能執行，Eager Execution模式一旦執行就會返回數值。這使TensorFlow 更容易入門，也使研發更直觀。

**Eager Execution 的優點如下：**

- 立即返回數值，方便除錯。
- 無需 Session.run() 就可以把它們的值返回到 Python。
- 為自定義和高階梯度提供強大支援。
- 幾乎所有 TensorFlow 運算都適用。

**TensorFlow 1.x 和 TensorFlow2.0比較：**
```
TensorFlow 1.x code:
>>> a = tf.constant(1)
>>> print(a)
Tensor("Const_5:0", shape=(), dtype=int32)

>>> sess = tf.Session()
>>> print("a = {}".format(sess.run(a)))
a = 1


TensorFlow 2.0 code:
>>> a = tf.constant(1)
>>> print(a)
tf.Tensor(1, shape=(), dtype=int32)
```

In [1]:
import numpy as np
import tensorflow as tf

print("Eager Execution 是否啟動: {}".format(tf.executing_eagerly()))

Eager Execution 是否啟動: True


In [6]:
a = tf.constant(3)
b = tf.constant(4)
c = tf.constant(50)
print(a.numpy)
print(b)
print("a = {}".format(a))
print("b = {}".format(b))
print(f"c = {c}")

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=3>>
tf.Tensor(4, shape=(), dtype=int32)
a = 3
b = 4
c = 50


In [3]:
x = tf.constant([[1, 2],[3, 4]], name='x')
y = tf.constant([[5, 6],[7, 8]], name='y')

tf_sum = x + y
tf_sub = x - y
tf_mul = x * y # element-wise
tf_div = x / y
tf_mod = x % y
tf_neg = -x

print("x: {}\n".format(x))
print("y: {}\n".format(y))
print("tf_sum: {}\n".format(tf_sum))
print("tf_sub: {}\n".format(tf_sub))
print("tf_mul: {}\n".format(tf_mul))
print("tf_div: {}\n".format(tf_div))
print("tf_mod: {}\n".format(tf_mod))
print("tf_neg: {}\n".format(tf_neg))

x: [[1 2]
 [3 4]]

y: [[5 6]
 [7 8]]

tf_sum: [[ 6  8]
 [10 12]]

tf_sub: [[-4 -4]
 [-4 -4]]

tf_mul: [[ 5 12]
 [21 32]]

tf_div: [[0.2        0.33333333]
 [0.42857143 0.5       ]]

tf_mod: [[1 2]
 [3 4]]

tf_neg: [[-1 -2]
 [-3 -4]]



In [8]:
import tensorflow as tf
x = tf.constant([[1, 2],[3, 4]], name='x')
y = tf.constant([[5, 6],[7, 8]], name='y')

tf_sum = tf.math.add(x, y)
tf_sub = tf.math.subtract(x, y)
tf_mul = tf.math.multiply(x, y)
tf_div = tf.math.divide(x,y)
tf_mod = tf.math.mod(x,y)
tf_neg = tf.math.negative(x)


print("x: {}\n".format(x))
print("y: {}\n".format(y))
print("tf_sum: {}\n".format(tf_sum))
print("tf_sub: {}\n".format(tf_sub))
print("tf_mul: {}\n".format(tf_mul))
print("tf_div: {}\n".format(tf_div))
print("tf_mod: {}\n".format(tf_mod))
print("tf_neg: {}\n".format(tf_neg))

x: [[1 2]
 [3 4]]

y: [[5 6]
 [7 8]]

tf_sum: [[ 6  8]
 [10 12]]

tf_sub: [[-4 -4]
 [-4 -4]]

tf_mul: [[ 5 12]
 [21 32]]

tf_div: [[0.2        0.33333333]
 [0.42857143 0.5       ]]

tf_mod: [[1 2]
 [3 4]]

tf_neg: [[-1 -2]
 [-3 -4]]



In [7]:
matrix1 = tf.constant([[1.0, 2.0],[3.0, 4.0]], name='x')
matrix2 = tf.constant([[5.0, 6.0],[7.0, 8.0]], name='y')

product = tf.linalg.matmul(matrix1, matrix2)
inv = tf.linalg.inv(matrix1)
trans = tf.linalg.matrix_transpose(matrix1)

print("product: {}\n".format(product))
print("inv: {}\n".format(inv))
print("trans: {}\n".format(trans))

product: [[19. 22.]
 [43. 50.]]

inv: [[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]

trans: [[1. 3.]
 [2. 4.]]



# Tensor Type
There are many data type in tensorflow. Following list some common type. If you want to change the type of tensor, ```tf.cast()``` can help. Please reference the following code.

| Python type | Description |  
| :------: | :------: |  
| tf.float32 | 32 bits floating point |
| tf.float64 | 64 bits floating point |
| tf.int8 | 8 bits signed integer |
| tf.int16 | 16 bits signed integer |
| tf.int32 | 32 bits signed integer |
| tf.int64 | 64 bits signed integer |
| tf.uint8 | 8 bits unsigned integer |
| tf.uint16 | 16 bits unsigned integer |
| tf.string | Variable length byte arrays. Each element of a Tensor is a byte array |
| tf.bool | Boolean |

In [14]:
x_float = tf.constant([1.8, 2.2], dtype=tf.float32)
x_int = tf.dtypes.cast(x_float, tf.int32)
# x_int = tf.dtypes.cast(x_float, "int32")
print("x_int: {}\n".format(x_int))

x_int: [1 2]



# Random Function

In [7]:
random1 = tf.constant(tf.random.normal([2,3],  mean=0.0, stddev=0.1))
random2 = tf.constant(tf.random.truncated_normal([2,3],  mean=0.0, stddev=0.1))
random3 = tf.constant(tf.random.uniform([2,3], minval=0, maxval=100))

print('random1: {}'.format(random1))
print('random2: {}'.format(random2))
print('random3: {}'.format(random3))

random1: [[ 0.12010022  0.00935003  0.07728565]
 [-0.13148463  0.06154595 -0.03777624]]
random2: [[-0.08179177  0.0260656   0.00617722]
 [ 0.0113455   0.0058369  -0.1083133 ]]
random3: [[53.962635  52.10936   86.221275 ]
 [40.57897   29.81571    1.0723948]]


# Constant Function

In [16]:
c1 = tf.zeros([2,1])
c2 = tf.ones([2,3])
c3 = tf.fill([2,4], 9)
c4 = tf.constant([2.0,1.0])
# c4 = tf.constant([[2.0,1.0]])
print('c1: {}'.format(c1))
print('c2: {}'.format(c2))
print('c3: {}'.format(c3))
print('c4: {}'.format(c4))


c1: [[0.]
 [0.]]
c2: [[1. 1. 1.]
 [1. 1. 1.]]
c3: [[9 9 9 9]
 [9 9 9 9]]
c4: [2. 1.]


# Constant/Variable  
Constant, variable, and placeholder can be set like the following. The difference among them is that 
1. constant can't be changed once define
2. variable would change while learning. It need to be initialized by constant tensorflow.

In [18]:
x_constant1 = tf.constant([[1.1, 2.2],[3.3, 4.4]], dtype=tf.float32) # define float32 tensor
x_constant2 = tf.zeros([2,3])
x_constant3 = tf.random.normal([1,3], stddev=1)

x_variable1 = tf.Variable(tf.constant([[1.1, 2.2],[3.3, 4.4]], dtype=tf.float32))
x_variable2 = tf.Variable(tf.zeros([2,3]))
x_variable3 = tf.Variable(tf.random.normal([1,3], stddev=1))

print(x_constant1)
print(x_constant2)
print(x_constant3)

print(x_variable1.numpy())
print(x_variable2)
print(x_variable3)

tf.Tensor(
[[1.1 2.2]
 [3.3 4.4]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor([[0.19554272 0.21895784 0.08463436]], shape=(1, 3), dtype=float32)
[[1.1 2.2]
 [3.3 4.4]]
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[ 1.6803914,  1.0050778, -0.5448439]], dtype=float32)>


# Common Function

In [19]:
import tensorflow as tf
x = tf.constant([[1., 5.], [-2., 3.]])
result1 = tf.reduce_mean(x)
result2 = tf.reduce_sum(x)
result3 = tf.math.abs(x)
print("result1: {}".format(result1))
print("result2: {}".format(result2))
print("result3: {}".format(result3))


result1: 1.75
result2: 7.0
result3: [[1. 5.]
 [2. 3.]]


In [20]:
test =tf.constant([[1.1, 2.2, 3.3],[4.5, 3.2, 2.1], [5, 0, -2]], dtype=tf.float32)
arg_max = tf.math.argmax(test)
arg_min = tf.math.argmin(test)
print("arg_max: {}".format(arg_max))
print("arg_min: {}".format(arg_min))

arg_max: [2 1 0]
arg_min: [0 2 2]


# Stack & Unstack
觀念和Numpy的stack,unstack相同(包含新增軸與axis軸向操作)

In [23]:
x = tf.constant([[0.7,0.9],[0.1,0.4],[0.5,0.8]], name='x')
print(x)
axis0_x = tf.unstack(x, axis=0)


print(axis0_x[0])
print(axis0_x[1])
print(axis0_x[2])

axis1_x = tf.unstack(x, axis=1)


print(axis1_x[0])
print(axis1_x[1])
# print(axis1_x[2])

tf.Tensor(
[[0.7 0.9]
 [0.1 0.4]
 [0.5 0.8]], shape=(3, 2), dtype=float32)
tf.Tensor([0.7 0.9], shape=(2,), dtype=float32)
tf.Tensor([0.1 0.4], shape=(2,), dtype=float32)
tf.Tensor([0.5 0.8], shape=(2,), dtype=float32)
tf.Tensor([0.7 0.1 0.5], shape=(3,), dtype=float32)
tf.Tensor([0.9 0.4 0.8], shape=(3,), dtype=float32)


In [24]:
x = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], name='x')
y = tf.constant([[1.0, 1.0], [0.0, 1.0], [1.0, 1.0]], name='y')

stacked_axis0_result = tf.stack([x,y], axis=0)
stacked_axis1_result = tf.stack([x,y], axis=1)


print(stacked_axis0_result)
print(stacked_axis0_result.shape)
    
print(stacked_axis1_result)
print(stacked_axis1_result.shape)

tf.Tensor(
[[[1. 2.]
  [3. 4.]
  [5. 6.]]

 [[1. 1.]
  [0. 1.]
  [1. 1.]]], shape=(2, 3, 2), dtype=float32)
(2, 3, 2)
tf.Tensor(
[[[1. 2.]
  [1. 1.]]

 [[3. 4.]
  [0. 1.]]

 [[5. 6.]
  [1. 1.]]], shape=(3, 2, 2), dtype=float32)
(3, 2, 2)


# TensorFlow Data

In [25]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
for elem in dataset:
    print(elem.numpy())

8
3
0
8
2
1


In [27]:
import tensorflow as tf
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
it = iter(dataset)

print(next(it).numpy())
print(next(it).numpy())
print(next(it).numpy())

8
3
0


In [28]:
import tensorflow as tf
x_data = tf.data.Dataset.from_tensor_slices([0, 1, 2, 3, 4, 5])
y_data = tf.data.Dataset.from_tensor_slices([0, 2, 4, 6, 8, 10])

for data1, data2 in zip(x_data, y_data):
    print('x: {}, y: {}'.format(data1, data2))

x: 0, y: 0
x: 1, y: 2
x: 2, y: 4
x: 3, y: 6
x: 4, y: 8
x: 5, y: 10


In [30]:
x_data.take(3)

<TakeDataset shapes: (), types: tf.int32>

In [29]:
x_data = tf.data.Dataset.from_tensor_slices([0, 1, 2, 3, 4, 5])
y_data = tf.data.Dataset.from_tensor_slices([0, 2, 4, 6, 8, 10])

for data1, data2 in zip(x_data.take(3), y_data.take(3)):
    print('x: {}, y: {}'.format(data1, data2))

x: 0, y: 0
x: 1, y: 2
x: 2, y: 4


In [32]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1.0, 2.0, 3.0, 4.0, 5.0]))
dataset = dataset.map(lambda x: x + 1) # 2.0, 3.0, 4.0, 5.0, 6.0
for data in dataset:
    print(data)
#     print(data.numpy())

tf.Tensor(2.0, shape=(), dtype=float64)
tf.Tensor(3.0, shape=(), dtype=float64)
tf.Tensor(4.0, shape=(), dtype=float64)
tf.Tensor(5.0, shape=(), dtype=float64)
tf.Tensor(6.0, shape=(), dtype=float64)


In [19]:
dataset = tf.data.Dataset.from_tensor_slices(np.arange(128))
dataset = dataset.batch(32)
for data in dataset:
    print(data)

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31], shape=(32,), dtype=int32)
tf.Tensor(
[32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55
 56 57 58 59 60 61 62 63], shape=(32,), dtype=int32)
tf.Tensor(
[64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87
 88 89 90 91 92 93 94 95], shape=(32,), dtype=int32)
tf.Tensor(
[ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113
 114 115 116 117 118 119 120 121 122 123 124 125 126 127], shape=(32,), dtype=int32)


In [35]:
dataset = tf.data.Dataset.from_tensor_slices(np.arange(128))
dataset = dataset.shuffle(200).batch(32) #將128個元素丟到200長度的陣列內，並隨機抽取32個元素當作batch
for data in dataset:
#     print(data.numpy())
    print(data)

tf.Tensor(
[ 98  22  39  12  99   2  81  38 103  95  17  90 112  70  37  14   6  54
  10  33  30  21  68  42  26  27  31 111  62 116  72  69], shape=(32,), dtype=int32)
tf.Tensor(
[  8  93  96  55  56  58   1  64 109   5  35 114  86  24   7 100  40  60
  79  41  85 101 113 108  50 105 119  25  80  61  88  83], shape=(32,), dtype=int32)
tf.Tensor(
[ 94  46  23 122 102  51  13  91  29  15  74  53 118 121 107  75  76 115
  45  71  18  66  89  19  65  59   3  73  97  28  47 126], shape=(32,), dtype=int32)
tf.Tensor(
[ 67 123  84  52  82  92  32  63  20 124  48  49  77  57   0   9 110 120
 125  11 106  87 117 127   4  78  16  43  36  34  44 104], shape=(32,), dtype=int32)


In [36]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5])
dataset = dataset.repeat(3) # 全部元素重複3次
for i in dataset:
    print(i)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


# Gradient  
使用with + GradientTape方法產生梯度向量，並且使用梯度向量物件內的gradient方法實作偏微分

In [40]:
w = tf.Variable(tf.constant([2.0]))

with tf.GradientTape() as t:
    loss = tf.math.exp(w)
#     loss = w * w
grad = t.gradient(loss,w)
print(grad)

#grad = t.gradient(loss,w)

tf.Tensor([7.389056], shape=(1,), dtype=float32)


In [39]:
a = tf.Variable(tf.constant([2.0]))
b = tf.Variable(tf.constant([3.0]))


with tf.GradientTape() as t:
    loss = 2*a**2 + 3*b**3
grad = t.gradient(loss,[a,b])
for i in grad:
    print(i)

tf.Tensor([8.], shape=(1,), dtype=float32)
tf.Tensor([81.], shape=(1,), dtype=float32)


In [41]:
w = tf.Variable(tf.constant([2.0]))

with tf.GradientTape() as t:
    loss = 4**w
grad = t.gradient(loss,w)
print(grad)

tf.Tensor([22.18071], shape=(1,), dtype=float32)


In [42]:
np.log(4)*4**2

22.18070977791825

In [43]:
w = tf.Variable(tf.constant([2.0]))

# 加了persistent=True才能重複使用這個t物件，否則用完即丟
with tf.GradientTape(persistent=True) as t:
    loss = w * w
grad = t.gradient(loss,w)
print(grad)
grad = t.gradient(loss,w)
print(grad)
del t

tf.Tensor([4.], shape=(1,), dtype=float32)
tf.Tensor([4.], shape=(1,), dtype=float32)


In [44]:
w = tf.constant([2.0])

with tf.GradientTape() as t:
    t.watch(w) # 非tf.variable的話就要加上 watch才能微分
    loss = w * w
grad = t.gradient(loss,w)
print(grad)

#grad = t.gradient(loss,w)

tf.Tensor([4.], shape=(1,), dtype=float32)
